package data;

/**
 *  This object stores a trade generated by the application
 */

public class Trade {
	
	private int tradeId;
	private long tradeTime;
	private String tradeType;
	private double tradeQty;
	private double tradePrice;
	private double tradePnL;
	private double cumulativePnL;
	
	public Trade(int tradeId, long tradeTime, String tradeType, double tradeQty, double tradePrice,	double tradePnL, double cumulativePnL)
	{
		this.tradeId = tradeId;
		this.tradeTime = tradeTime;
		this.tradeType = tradeType;
		this.tradeQty = tradeQty;
		this.tradePrice = tradePrice;
		this.tradePnL = tradePnL;
		this.cumulativePnL = cumulativePnL;
	}
	
	public Trade()
	{
		
	}
	
	public int getTradeId() {
		return tradeId;
	}
	public void setTradeId(int tradeId) {
		this.tradeId = tradeId;
	}
	public long getTradeTime() {
		return tradeTime;
	}
	public void setTradeTime(long tradeTime) {
		this.tradeTime = tradeTime;
	}
	public String getTradeType() {
		return tradeType;
	}
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}
	public double getTradeQty() {
		return tradeQty;
	}
	public void setTradeQty(double tradeQty) {
		this.tradeQty = tradeQty;
	}
	public double getTradePrice() {
		return tradePrice;
	}
	public void setTradePrice(double tradePrice) {
		this.tradePrice = tradePrice;
	}
	public double getTradePnL() {
		return tradePnL;
	}
	public void setTradePnL(double tradePnL) {
		this.tradePnL = tradePnL;
	}
	public double getCumulativePnL() {
		return cumulativePnL;
	}

	public void setCumulativePnL(float cumulativePnL) {
		this.cumulativePnL = cumulativePnL;
	}
}
